USE master

GO

CREATE DATABASE DB_FINTECH

GO

USE DB_FINTECH
GO

CREATE TABLE TB_USUARIO (
	ID INT NOT NULL IDENTITY(1,1),
	NOME NVARCHAR(50) NOT NULL,
	CPF NVARCHAR(11) NOT NULL,
	DATA_NASCIMENTO DATETIME2 NOT NULL,
	EMAIL NVARCHAR(150) NOT NULL,
	TELEFONE NVARCHAR(20) NOT NULL,
	USUARIO NVARCHAR(50) NOT NULL, --CLIENTE -> AGENCIA + CONTA | ADMINISTRADOR -> USUÁRIO PRÓPRIO
	SENHA NVARCHAR(40) NOT NULL,
	DATA_ULTIMO_ACESSO DATETIME2,
	TIPO_USUARIO CHAR(1) NOT NULL,
	NUMERO_TENTATIVAS_ACESSO INT NOT NULL
	PRIMARY KEY(ID),
	CHECK(TIPO_USUARIO = 'A' OR TIPO_USUARIO = 'C') --A: ADMINISTRADOR, C: CLIENTE
)
GO
CREATE TABLE TB_CONTA (
	ID INT NOT NULL IDENTITY(1,1),
	ID_USUARIO INT NOT NULL,
	AGENCIA NVARCHAR(4) NOT NULL,
	NUMERO_CONTA NVARCHAR(20) NOT NULL,
	SALDO FLOAT DEFAULT 0,
	--LIMITE FLOAT DEFAULT 1000,
	SENHA_PAGAMENTO NVARCHAR(6),
	ATIVO BIT DEFAULT 1,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(ID),
	CHECK(SALDO >= 0)
)
GO
CREATE TABLE TB_CARTAO (
	ID INT NOT NULL IDENTITY(1,1),
	ID_CONTA INT NOT NULL,
	NUMERO_CARTAO NVARCHAR(30) NOT NULL,
	CVV NVARCHAR(3) NOT NULL,
	VALIDADE_CARTAO DATETIME2 NOT NULL,
	ATIVO BIT DEFAULT 1,
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTA(ID),
 
	PRIMARY KEY(ID),
)
GO
 
CREATE TABLE TB_TIPO_CHAVE_PIX(
	ID INT NOT NULL IDENTITY(1,1),
	TIPO VARCHAR(20),
	PRIMARY KEY(ID)
)
GO
CREATE TABLE TB_CHAVE_PIX(
	ID INT NOT NULL IDENTITY(1,1),
	ID_CONTA INT NOT NULL,
	TIPO_CHAVE INT NOT NULL,
	CHAVE_PIX VARCHAR(50) NOT NULL,
	ATIVO BIT DEFAULT 1,
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CONTA) REFERENCES TB_CONTA(ID),
	FOREIGN KEY(TIPO_CHAVE) REFERENCES TB_TIPO_CHAVE_PIX(ID),
)

GO

CREATE TABLE TB_STATUS_MOVIMENTACAO(
	ID INT NOT NULL IDENTITY(1,1),
	NOME_STATUS VARCHAR(20)
	PRIMARY KEY(ID),

)
GO
 
CREATE TABLE TB_TIPO_MOVIMENTACAO (
	ID INT NOT NULL IDENTITY(1,1),
	NOME NVARCHAR (50) NOT NULL,
	PERCENTUAL_TAXA FLOAT NOT NULL,
	CHECK(PERCENTUAL_TAXA >= 0),
	PRIMARY KEY(ID),
)
GO
 
CREATE TABLE TB_MOVIMENTACAO(
	ID INT NOT NULL IDENTITY(1,1),
	ID_CONTA_ORIGEM INT NOT NULL,
	ID_TIPO_MOVIMENTACAO INT NOT NULL,
	ID_STATUS_MOVIMENTACAO INT NOT NULL,
	DESTINO VARCHAR(50) NOT NULL,
	DATA_HORA DATETIME2 NOT NULL,
	VALOR_MOVIMENTACAO FLOAT NOT NULL,
	DESCRICAO VARCHAR(100) NULL,
	VALOR_TAXA_APLICADA FLOAT NULL,
	VALOR_TOTAL FLOAT NOT NULL
	PRIMARY KEY(ID),
	FOREIGN KEY(ID_CONTA_ORIGEM) REFERENCES TB_CONTA(ID),
	FOREIGN KEY(ID_TIPO_MOVIMENTACAO) REFERENCES TB_TIPO_MOVIMENTACAO(ID),
	FOREIGN KEY(ID_STATUS_MOVIMENTACAO) REFERENCES TB_STATUS_MOVIMENTACAO(ID),
 
)
GO