SELECT * FROM TB_CONTA
GO
SELECT * FROM TB_USUARIO
SELECT * FROM TB_ENDERECO
SELECT * FROM TB_CARGOS
SELECT
	C.ID,
    C.AGENCIA,
    C.NUMERO_CONTA,
	U.NOME,
    M.DATA_HORA as [ULTIMA MOVIMENTACAO],
    U.DATA_ULTIMO_ACESSO as [ULTIMO ACESSO],
    C.ATIVO
FROM 
    TB_USUARIO U
    INNER JOIN TB_CONTA C ON U.ID = C.ID_USUARIO
    INNER JOIN TB_MOVIMENTACAO M ON C.ID = M.ID_CONTA
WHERE 
    M.DATA_HORA = (SELECT MAX(DATA_HORA) FROM TB_MOVIMENTACAO
						WHERE ID_CONTA = C.ID);

	INSERT INTO TB_MOVIMENTACAO (
    STATUS_MOVIMENTACAO, 
    ID_CONTA, 
    TIPO_MOVIMENTACAO, 
    DIRECAO, 
    DATA_HORA, 
    DESCRICAO, 
    VALOR_MOVIMENTACAO, 
    VALOR_PERCENTUAL_TAXA, 
    VALOR_TOTAL, 
    CODIGO_MOVIMENTACAO
    ) VALUES
('PENDENTE', 11, 'Pix', 'CREDITO', GETDATE(), 'Transferencia pix - barzin sexta', 50, 0, 50, 'bb217d4a-01a8-43a7-8507-fc9b07f0d3a9'),
('PENDENTE', 12, 'Pix', 'DEBITO', GETDATE(), 'Transferencia pix - barzin sexta', 50, 0, 50, 'bb217d4a-01a8-43a7-8507-fc9b07f0d3a9');

GO

SELECT * FROM TB_CONTA


